server:
  port: 8082

#eureka:
#  client:
#    serviceUrl: #注册中心的注册地址
#      #      defaultZone: http://106.75.115.170:8090/eureka/
#      defaultZone: http://192.168.1.101:8090/eureka/

spring:
  application:
    name: mybatis-plus

  datasource:
    url: jdbc:mysql://106.75.115.170:3306/gn-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: gwk_632697105qq
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 80
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
      #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
      test-on-borrow: true
      test-while-idle: true



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

